# This file enables the Travis continuous integration system, which
# automatically builds and tests joda-time for each GitHub commit or 
# pull request on three separate JDKs.
#
# For more information, see https://travis-ci.org

language: scala

sudo: false

jdk: 
  - oraclejdk8

script:
  - sbt mimaReportBinaryIssues
